### ISSUE TITLE
SubmitButton react-native | wrong type on textStyle prop | Type '{ color: string; fontFamily: string; }' has no properties in common with type 'TextProps'.

### ISSUE THREAD

**Issue by nunofernandes08** [checkout/frames-react-native#15]
When i try to apply some style to our textStyle i get the following error: 

<img width="741" alt="Screenshot 2022-05-26 at 14 50 17" src="https://user-images.githubusercontent.com/64104569/170501154-e4143786-f4ec-497a-a5ff-fdf0f242c5ba.png">

What i suggest to do is change the type TextProps to StyleProp < TextStyle >.

**Comment by dani-z** [comment]
This was fixed in https://github.com/checkout/frames-react-native/pull/21
