### ISSUE TITLE
3DS integration

### ISSUE THREAD

**Issue by mark-quinn** [checkout/frames-react-native#3]
Just wondering if there are any integration guides on implementing 3DS checkout? Can only see this being mentioned in the respective native packages for both platforms.

**Comment by ioan-ghisoi-cko** [comment]
Hi. This is still in our backlog, however, I can share the logic of handling 3DS on mobile:
1. obtain the card token from Frames React Native 
2. send the token to your server-side and send a 3DS payment request (you can specify the success/failure URL that you want the customer to be redirected to after 3DS)
3. return the 3DS URL you get from the payment response to your app
4. in the app open a webview with the 3DS URL
5. after the customer completes 3DS they will be redirected to the success/failure URL you set, so from the app perspective you can simply add a URL change handler for the webview and whenever the webview has the success/fail URL dismiss it and show a success/fail outcome to your customer in your "native" app

*in case a URL change handler is not usable you can host your own outcome page and use the Post Message API to tell the "native" app about the outcome. 

The plan is to add the webview interaction in the SDK, and handle the logic on our end but in case you need this earlier this is likely the logic that will be used.

**Comment by mark-quinn** [comment]
@ioan-ghisoi-cko thanks for the quick response! Yeah that's roughly how it's been implemented on our end just now. Thanks for the update, looking forward on seeing it within this SDK, will close this issue 👍

**Comment by AnubhavGenx** [comment]
@ioan-ghisoi-cko Hi. I am using your frames-react-native library in my react native app. I am also stuck at the bank authentication and getting the key if the authentication is successfull or not.
 Are you guys have any plans on continuing on this library and adding the logics in your sdk?
