### ISSUE TITLE
On blur event returns `undefined` on an actual device

### ISSUE THREAD

**Issue by mark-quinn** [checkout/frames-react-native#5]
The wrapped text input components in the source seem to be returning `undefined` from the native event text value `e.nativeEvent.text` for `onBlur`. I have tested this with `CardNumber`, `ExpiryDate` and `Cvv`.

I am thinking it could be along the lines of an updated React Native version against the one used in this package but haven't investigated fully. For reference I am using RN version `0.66.3`. The simulator seems to handle the event correctly, not sure if that's anything to go on.

**Comment by waleedshkt** [comment]
`onBlur` doesn't return a value. So the `undefined` error is unsurprisingly inevitable. 

There are indeed some limitations to what you can do with the Frames components. I think for now you cannot straight away get the card values. The only option for now is the `cardTokenized` handler.

Currently, Frames is great to get up and running receiving payments in no time. But the biggest challenge arises when one tries to incorporate Frames components with the billing form (handling validation of billing info along with card details).
