### ISSUE TITLE
Discover card displayed as mastero in card number text box

### ISSUE THREAD

**Issue by gaurav-tally** [checkout/frames-react-native#7]
Hi,

We are implementing checkout frame SDK in our project, while testing with Discover card, the card scheme displayed as maestro. I am attaching Screen-short for reference.

![Screenshot_20220210-212023](https://user-images.githubusercontent.com/83930956/153753717-50f78e53-459f-4273-bbed-e5ca3ddac40b.jpg)

**Comment by waleedshkt** [comment]
Better modify the module code to remove schemes detection altogether and patch it for now.

**Comment by waleedshkt** [comment]
@ioan-ghisoi-cko 

Maestro cards must be detected in the end (with the least preference) if there are other cards in the range of 60-69 like Discover

**Comment by ioan-ghisoi-cko** [comment]
Fixed in the latest release (1.1.3)
